[package]
name = "notifications-dbus-mon"
version = "1.0.0"
edition = "2021"

[dependencies]
arboard = "3.4.1"
futures-util = "0.3.30"
rand = "0.8.5"
regex = "1.10.6"
tokio = { version = "1.40.0", features = ["full"] }
zbus = { version = "4.4.0", features = ["tokio"] }
